### ISSUE TITLE
start OneNoteMdExporter.exe happen a issue

### ISSUE THREAD

**Issue by charlesgogo01** [alxnbl/onenote-md-exporter#62] opened 2022-05-07 01:32 UTC
**Describe the bug**

**To Reproduce**

![image](https://user-images.githubusercontent.com/32640053/167232720-b0a94fcb-4da4-4f1f-9bc6-672e5fd81029.png)

Steps to reproduce the behavior.
Ideally, export a basic OneNote notebook (.onepkg) that can be use to reproduce the issue. Tutorial to export .onepkg file is [available here](/doc/notebook-onepkg-export.md).

**Expected behavior**

**Logs**
Join the "logs.txt" log file located in the directory of the tool. 
⚠️ Ensure that the log file do not contain any personal data ⚠️

**Desktop (please complete the following information):**
 - Windows version : 10 64 bits
 - Office Version : 2019  onenote 2016 64 bits

**Additional context**

**Comment by alxnbl** [comment] 2022-05-07 08:05
Hey @charlesgogo01 , could you give me some more details about the bug please. Like the command line you are using to start the app for example. Thanks

**Comment by alxnbl** [comment] 2022-05-09 15:11
Thanks. Surprising, it looks like an issue specific to you configuration.
Could you join the logs.txt file that should be created next to the exe file please.

**Comment by charlesgogo01** [comment] 2022-05-18 11:40
log is null； i found a  app crash！  the report is：
`Version=1
EventType=APPCRASH
EventTime=132973472992057546
ReportType=2
Consent=1
UploadTime=132973472995977896
ReportStatus=268435456
ReportIdentifier=349c98e7-c937-4fa7-8de0-4f7a167c5995
IntegratorReportIdentifier=b2d2f131-edb1-42e8-9712-93a99976f519
Wow64Host=34404
NsAppName=OneNoteMdExporter.exe
OriginalFilename=OneNoteMdExporter.dll
AppSessionGuid=000043d4-0001-002e-b431-d24dab6ad801
TargetAppId=W:000611e0f2625eddae9cc24f35494436bf8d00000000!0000aa9717e37f2f063b01dce7a6dae1fb8f69e90ec7!OneNoteMdExporter.exe
TargetAppVer=2021//11//16:04:43:46!0!OneNoteMdExporter.exe
BootId=4294967295
TargetAsId=5944
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=e1815a2aa0ef410b57becb7218c711be
Response.BucketTable=4
Response.LegacyBucketId=1711028599349776830
Response.type=4
Sig[0].Name=app name
Sig[0].Value=OneNoteMdExporter.exe
Sig[1].Name=app ver
Sig[1].Value=1.2.0.0
Sig[2].Name=app timestamp
Sig[2].Value=61933702
Sig[3].Name=error module
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=error module version
Sig[4].Value=10.0.19041.1645
Sig[5].Name=error module  timestamp
Sig[5].Value=630193b4
Sig[6].Name=error code
Sig[6].Value=e0434352
Sig[7].Name=Anomalous Offset
Sig[7].Value=0000000000034f69`

**Comment by alxnbl** [comment] 2022-10-25 19:58
Hey, I encountered this issue on a computer on which the office installation was corrupted. I solved the issue by running the office repair utility, reboot, and restart the tool. Cf: https://support.microsoft.com/en-us/office/repair-an-office-application-7821d4b6-7c1d-4205-aa0e-a6b40c5bb88b .

By the way I will update the code in the next version to display a recommandation of doing this repair when a exception occurs during startup.

Could you try this solution and give me a feedback ?

**Comment by alxnbl** [comment] 2022-10-25 19:59
Duplicate of #65

**Closed by alxnbl** 2022-10-25 19:59 UTC
Labels: bug, duplicate
