### ISSUE TITLE
Exported picture bad format when nested into a table

### ISSUE THREAD

**Issue by Bratieres** [alxnbl/onenote-md-exporter#87] opened 2023-07-08 20:05 UTC
**Describe the bug**
Some embedded pictures in OneNote when imported into Joplin have bad syntax format :

""!\[image1\](:/e887b8c3c94f417cb877b0ae5f264510)"" instead of ""![image1](:/e887b8c3c94f417cb877b0ae5f264510)""

As display is interpreted, even with double quotes, I explain it : there is an explicit backslash before [ and ]

**To Reproduce**

Steps to reproduce the behavior.
Ideally, export a basic OneNote notebook (.onepkg) that can be use to reproduce the issue. Tutorial to export .onepkg file is [available here](/doc/notebook-onepkg-export.md). (zip of page export)

**Expected behavior**
No backslash arround brackets, removing backslash makes picture be OK.

Attached file is exported page having this problem. Others pages of this notebook are OK and some pictures (the last ones) of this page are OK too.

**Logs**
Join the "logs.txt" log file located in the directory of the tool. 
⚠️ Ensure that the log file do not contain any personal data ⚠️

**Desktop (please complete the following information):**
 - OneNodeMdExporter version : 1.3.0
[PP4 Chaufferie.zip](https://github.com/alxnbl/onenote-md-exporter/files/11992321/PP4.Chaufferie.zip)
[logs.txt](https://github.com/alxnbl/onenote-md-exporter/files/11992324/logs.txt)

 - Windows version : 11 /64 bits
 - Office Version : 365/64 bits

**Additional context**

**Comment by alxnbl** [comment] 2023-09-01 12:57
Thank for your report. Sorry but I will be very busy the next few months and will not be able to have a look to the issue. Hopefully, a kind contributor will take a look at your problem.

**Comment by Bratieres** [comment] 2023-09-20 19:43
Have had a new look to this. It seems it happens in tables only 
----
![image2](:/ff87503a205644719d6f5fa65fae91b6) alone :  works and displays image BUT
----
<table>
![image2](:/ff87503a205644719d6f5fa65fae91b6)
<colgroup>
Does not display picture but text ![...

**Comment by alxnbl** [comment] 2023-09-20 20:17
Indeed, it is a known limitation / bug of the tool. I insert markown image reference inside HTML table, which is not valid markdown. To be corrected in the future but I do not have an easy solution right not to fix it.

**Comment by alxnbl** [comment] 2023-09-22 19:26
Duplicate of #48

**Closed by alxnbl** 2023-09-22 19:26 UTC
Labels: bug, enhancement
