### ISSUE TITLE
exe file does not do anything

### ISSUE THREAD

**Issue by letscho123** [alxnbl/onenote-md-exporter#10] opened 2021-01-30 16:06 UTC
I followed all the steps from the installation guide, but when I click on the .exe file, nothing happens. I tried it on two different PCs. Opening the .exe file with admin rights did not help. Could the problem be that I am not using Onenote 2016, but 365? I tried, but I could not go back to Onenote 2016.

The logs seem to be very strange and partly in French, but my system language is English.
[OneNoteMdExporter.log](https://github.com/alxnbl/onenote-md-exporter/files/5898254/OneNoteMdExporter.log)

**Desktop (please complete the following information):**
 - Windows version : 10 64 bits
 - Office Version : 365 64 bits
 - Onenote: 16.0.13530.20418 64 bits
 - PanDoc Version : 2.11.4
 - OneNote Md Exporter - v0.2.1.0

**Comment by alxnbl** [comment] 2021-01-30 19:58
Indeed, the log file is from the original binary archive. I should have remove it. I will correct that in the next release.

Could you try to launch a console (cmd.exe), go to the directory where you unzip the app (cd <FolderPath>) and then start "alxnbl.OneNoteMdExporter.exe" and send me screenshot of the result ?

Note : you should not run the CMD as an administrator.

**Comment by letscho123** [comment] 2021-01-31 11:07
Here is the output of the console:

> A fatal error occurred. The required library hostfxr.dll could not be found.
> If this is a self-contained application, that library should exist in [C:\Users\username\Downloads\OneNoteMdExporter.v0.2\].
> If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].
> 
> The .NET runtime can be found at:
>   - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=5.0.1

In my case, the dotnet folder is located in [C:\Program Files (x86)\dotnet].

**Comment by alxnbl** [comment] 2021-01-31 14:40
I publish a new version 0.3 that now embed its dependencies to the DotNet framwork. 
Could you test again and see if its works ? 
I have not yet tested the tool on Office 365 so I am interested by about the result.

**Comment by letscho123** [comment] 2021-01-31 14:58
The program works now, but I cannot export anything. I tried with Markdown folder and Joplin folder using a very simple test notebook (I also tried another notebook). I get following output and only empty files:

> ***************************************
> Start exporting notebook: test
>  ***************************************
> --> Found 1 sections and sections groups 
>                                                                                                                                                                                                        Start processing section (1/1) :  test\New Section 1\New Section 1
>    Page 1/1 : test
> Error during processing of page test [1633505d22a442299859eb802c90e80b]. Page ignored. Error message : 0x80042006
> 
> --> Notebook export successful
> Export folder : 'C:\Users\username\Downloads\OneNoteMdExporter.v0.3.0-x86\test'
> 
> Press a key to exit...        

Do you have any idea how I can get Onenote2016? I tried to install it, even by uninstalling office 365 before, but I end up always with the same version.

BTW: Thanks a lot for your help!

**Comment by alxnbl** [comment] 2021-01-31 15:05
Cool it solves your first issue.
You now have the same problem than the issue #9 .
Could you join your OneNoteMdExporter.log file stp. Maybe it will give me a clue on where to look...

About Office version, no idea but I am wondering if an Office365 license allows you to activate Office 2016.
You confirm that your Office 365 license is correctly activated on your computer ?

**Comment by letscho123** [comment] 2021-01-31 15:18
Here you go:

> 2021-01-31 15:50:41.458 +01:00 [INF] Start exporting notebook: test
> 2021-01-31 15:50:41.458 +01:00 [INF] ***************************************
> 2021-01-31 15:50:41.464 +01:00 [INF] --> Found 1 sections and sections groups
> 
> 2021-01-31 15:50:41.470 +01:00 [INF] Start processing section (1/1) :  test\New Section 1\New Section 1
> 2021-01-31 15:50:41.483 +01:00 [INF]    Page 1/1 : test
> 2021-01-31 15:50:41.501 +01:00 [ERR] Error during processing of page test [1633505d22a442299859eb802c90e80b]. Page ignored. Error message : 0x80042006
> System.Runtime.InteropServices.COMException (0x80042006): 0x80042006
>    at Microsoft.Office.Interop.OneNote.ApplicationClass.Publish(String bstrHierarchyID, String bstrTargetFilePath, PublishFormat pfPublishFormat, String bstrCLSIDofExporter)
>    at alxnbl.OneNoteMdExporter.Services.Export.JoplinExportService.ExportSection(Node section) in C:\Src\GitH\onenote-md-exporter\src\Services\Export\JoplinExportService.cs:line 98
> 2021-01-31 15:50:41.512 +01:00 [INF] 
> 2021-01-31 15:50:41.513 +01:00 [INF] --> Notebook export successful
> Export folder : 'C:\Users\username\Downloads\OneNoteMdExporter.v0.3.0-x86\test'
> 2021-01-31 15:50:41.513 +01:00 [INF] 
> 2021-01-31 15:50:41.513 +01:00 [INF] 
> Press a key to exit...

Yes, I have an enterprise version of Office 365. I will ask my company if I can go back to Onenote 2016.

**Comment by alxnbl** [comment] 2021-02-01 07:52
Thanks.
Not sur that going back to OneNote 2016 will solve the issue. So if you can, try on another computer before uninstalling your current version to not waste time...

The log file let me think that the error could be caused by some access right permission. I will release a new version to try to by-pass this issue.

**Comment by alxnbl** [comment] 2021-02-01 08:37
You can test again with release 0.3.1 🤞

**Comment by letscho123** [comment] 2021-02-01 09:39
Same issue with version 0.3.1

I will try tonight on another PC. I also don't think that the Onenote version is an issue since the notes are saved in 2010-2016 notebook format.

**Comment by letscho123** [comment] 2021-02-01 21:03
I tried it on my private PC and also with removing my work account (hence unlicensed), but I always get the same error code.

**Comment by alxnbl** [comment] 2021-02-02 12:02
Thank you for your test, maybe I miss something in the way I use the OneNote API... I will look deeper once I have free time. 
Meanwhile, I would be curious to know if the import from OneNote function of EverNote works on your computer, because I am pretty sur EverNote rely on the same APIs than my tool. 
If you don't mind, you can do the test with this version of EverNote : https://help.evernote.com/hc/en-us/articles/360052560314-Install-an-older-version-of-Evernote (last version no longer support OneNote import).

**Comment by alxnbl** [comment] 2021-02-02 15:14
Good news, I have been able to reproduce the issue on an other computer. It will be easier for me to find a fix. 
I will keep you inform in next few days.

**Comment by alxnbl** [comment] 2021-03-03 09:02
Hey @letscho123 , I tried to fix the OneNote error issue in a Beta release available here : 
https://github.com/alxnbl/onenote-md-exporter/releases/tag/v0.4.0-Beta1

Could you please give it a try ? Thanks

**Comment by letscho123** [comment] 2021-03-03 10:47
Thanks a lot for the update!

The export works now, but I have a problem with images. They are created in the ressources folder, but in Joplin they are referred to as (tmp/media/image1.png). This happens when I use Joplin export. With markdown export the ressources folder stays empty.

Another issue is that the page hierarchy is not preserved. This means that sub-pages have '--' signs, but the ordering from Onenote is lost.

**Comment by alxnbl** [comment] 2021-03-03 23:53
Great that It solve your first issue !
About the page hierarchy, it is preserved only with Joplin Export, not markdown Export. I have tested today and it works fine on my side.
Regarding image, could you open a new issue with more detailed to reproduce the error. For information, I have fixed an issue with image in Md Export in release 0.4.0 Beta2.

**Comment by alxnbl** [comment] 2021-03-04 19:18
I close the issue, could you open a new one if you still encounter other issues.
Thanks

**Closed by alxnbl** 2021-03-04 19:18 UTC
Labels: bug

**Comment by abhishekpatel-surat** [comment] 2023-08-07 06:49
Can Any one help me to resolve this below error in One note 2016
Error Message - 0x80042006
   Stack Trace -    
   at Microsoft.Office.Interop.OneNote.IApplication.OpenHierarchy(String bstrPath, String bstrRelativeToObjectID, String& pbstrObjectID, CreateFileType cftIfNotExist)
   at ConversionLibrary.Modules.OneNotePlugin.Print() in E:\DevOps\Agent_Net6-Service\_work\1\s\code\Framework\Casepoint.Conversion.Core\Modules\OneNote\OneNotePlugin.cs:line 113
